### ISSUE TITLE
index.tsx hardcoded path

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/create-react-app#35]
In my app, I wanted to have a clear separation between server and client code,
so i moved the index.tsx to src/client/ . This resulted in errors on npm start.
(and there is no possilibity for configuration)

**Comment by Maartenvm** [comment]
To be clear, let's not make this a discussion on whether it's smart to have server and client in one app, but rather on whether it is a good idea to have a hardcoded path to the index.

my proposed solution is an applicationEntryPoint (or similar) variable in package.json

**Comment by sverhoeven** [comment]
To have clear separation use https://lernajs.io/ with this you can have multiple package.json in your repo.
For example 
- package.json , for server code
- packages/common/package.json, for code shared between client and server
- packages/client/package.json, for client code

This will not be fixed upstream because of their [core ideas](https://github.com/facebookincubator/create-react-app/blob/master/CONTRIBUTING.md#core-ideas)
the alternative is to `npm run eject` and update the configuration to how you want them.
